version: "2.2"
services:
  jobmanager:
    image: flink:1.17.1-scala_2.12-java11
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager     
    volumes:
      - /home/alvaro/Desktop/CloudComputing/ApacheFlinkCode/flink/files:/files
      - /home/alvaro/Desktop/CloudComputing/ApacheFlinkCode/flink/flink-examples:/flink-examples

  taskmanager:
    image: flink:1.17.1-scala_2.12-java11
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 2
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2 
    volumes:
      - /home/alvaro/Desktop/CloudComputing/ApacheFlinkCode/flink/files:/files


